### ISSUE TITLE
windows 10  send apk (Trials.Fusion) CE-36441-8  occured，but everything is ok when transfer apk via ftp and install.

### ISSUE THREAD

**Issue by liang-chang** [marcussacana/DirectPackageInstaller#26]
windows 10  send apk (Trials.Fusion) to PS4  CE-36441-8  error code occured，but everything is ok when transfer apk via ftp and install.
OS：windows 10 22H2
app version:6.1.14

**Comment by marcussacana** [comment]
Because of my job I don't have time for keep the tool for a while, but left the issue open, one day I will check it

**Comment by liang-chang** [comment]
This is very strange, when I redownloaded and upgraded online to 6.1.15, it worked! 
This issue may be closed. I don't know what happened.

**Comment by marcussacana** [comment]
If the DPI detected any erros a log file should appears in the program directory, you may send that as report.

**Comment by caioob** [comment]
Hi, is it possible to reopen this issue? I'm experiencing the same problem. 

I have a few more observations that might be useful:
- The problem appears to happen when installing the pkg, after the download is finished. Tested with a smaller pkg that doesn't have  a "ready to play" state and it fails by the end of the process, which I assume is the installation step. On bigger packages that become playable after a portion is downloaded the error occurs when it reaches the playable threshold, which is also an indication to be failing during the installation process
- The issue seems to be with backup pkg only, when installing a homebrew package like RPI via DPI it works flawlessly
- As mentioned previously, installing the package locally on the PS4 works, so it's not a problem with the source pkg, but might be an issue with the pkg when uploaded to the console
- Other remote installers cause the same error. Happens when downloading a direct link or when sending a downloaded pkg from the pc
- Tried 3 different platforms and got the same error on 3: *Windows, Android and Arch Linux*

I'm attaching logs of an attempt of sending a pkg from the pc, running the windows client and using goldhen binloader server on the PS4. If any other logs or scenarios might be useful to test I'm available to help 

[DPIServer.log](https://github.com/user-attachments/files/20087231/DPIServer.log)

**Comment by marcussacana** [comment]
Hi, thanks for the detailed info.

As you said, you can see that other remote installers have the same issue. Once you repack the FPKG, it may solve the error — that’s why we usually say it’s a problem with the package.

The reason it works with FTP is because the installation method is different from the one used in Download Mode. When you copy the game via FTP, it uses the same installation method as USB, which is a debug (test) function Sony implemented on the PS4 to test games. This means the PS4 doesn’t need to perform as many security and sanity checks. As a result, you can install many PKGs that fail in Download Mode, because the download method was not made for testing — the PS4 performs a lot of verification steps, which can result in obscure installation errors.

The "workaround" for this issue would be for DPI to avoid relying on PS4 BGFT and instead transfer the entire game by itself. While this is possible, you lose things like the PS4 download notification with progress tracking, and there's no guarantee the file wasn’t corrupted during transfer.

At the end of the day, it just seems better to repack the FPKG correctly. This is the reason you see the same error with all installer tools — because they all rely on the remote package installer. Even DPI, which uses a payload-based method, still relies on the same internal PS4 functions. Everything is ultimately handled by the PS4 system.

What I can ask you to try in this case:

You have this PKG — can you try extracting and rebuilding it using an updated FPKG tool?

**Comment by caioob** [comment]
> You have this PKG — can you try extracting and rebuilding it using an updated FPKG tool?

Sure! I'll look into how to do so. Do you know what I should probably search to figure out how to rebuild the pkg?

**Update:**
I extracted the pkg file and repackaged following the FPKG Tool [README](https://github.com/CyB1K/PS4-Fake-PKG-Tools-3.87/blob/main/README.md) and got the same error :/

**Comment by marcussacana** [comment]
send the original pkg to my email ddtank.marcus[at]gmail.com
