### ISSUE TITLE
The application crashed when sending the payload of big games

### ISSUE THREAD

**Issue by ominchan** [marcussacana/DirectPackageInstaller#38]
I tried the app to day (on windows) and i installed Cuphead straight out from 1fichier, it worked, it was sent to the ps4 and installed the game. But when i tried to install mortal kombat 11, wich is around 36 gb but the app just froze (turned white), same thing happened while trying to install NBA 2k22. And i reckon it will happen if i try to install any other big app. I should mention that the disk space was kinda full on the 800 something hard drive but it was sufficient to install said game

**Comment by marcussacana** [comment]
That's because you are using the '1fichier' for free and it was limitation by the 1fichier itself that make the DPI go unresponsive.
Still working but seems to be froze and if you wait time enought it will download the entire game then unfreeze and finally send the payload to start the PS4 transfer.

There's 2 ways to solve this problem:
1 - Download in browser the game and then use the DPI to install it latter.
2 - Use Alldebird (paid) service, you can get your account personal API key and put in the DirectPackageInstaller API, in this case it will works without freeze and download without need be from the browser.
