### ISSUE TITLE
MacOS versions incorrectly built/bundled

### ISSUE THREAD

**Issue by HVR88** [marcussacana/DirectPackageInstaller#46]
There is no way to make any MacOS download work as they're not bundled correctly.

Testing on Macbook Air M1

"APP" version:
The file structure has windows path delimiters (back slash) hard-coded into filenames, which prevents them from being recognized as path delimiters on the Mac when unzipped. This just makes a mess of super-long filenames that nothing can be done with.

Non-APP version:

No way to launch executable from finder or terminal. It just plain doesn't work.

I'd suggest the long road of refactoring the whole thing to not use .NET and instead develop as an Electron app to support multiple build targets with all dependencies included. IMO, even the Windows builds are a mess right now with over a dozen files and libraries inside the archive.

**Comment by marcussacana** [comment]
I need details why it does not works from terminal
The bundled version is really deprecated, but it should at least works for send direct links.
Can you say what path it tries to access with the back slash?, the tool works on linux so it shouldn't be a problem like that on macos.
the MacOS is pretty unstested since a time ago, I did the initial tests on a hackintosh installation and just keep unchanched as possible, but the system updates, dotnet updates and avalonia updates can brick it anytime anyway, so this might be the problem.

To the CLI version works you should try give `chmod +x` and be sure that the command `dotnet` works, in last case execute DPI directly with help of the dotnet with `dotnet DirectPackageInstaller.Desktop.dll` this should bypass executable permissions problems

**Comment by marcussacana** [comment]
For the unzip problem, I recommend trying the github action build as well, since the Github Env is an linux the zip should be done in a way that works for your extractor.
But this type of thing is more a fault of the compressor and decompressor than mine, if the compressor changed the path deliminator it should solve the problem for both system, if the decompressor detect the incompatible deliminator it should works as well.

**Comment by HVR88** [comment]
Using Automator I've made a little applet that can be double-clicked in Finder to open the app. It's a wrapper around a simple bash script that just copies the dotnet launch you mentioned above, with full paths to dotnet and the dll.

Because none of the files are signed, this required opening the applet 4 or 5 times, each time authorizing a differed dynamic library in security settings.

But now it's easy to open.  Still need to test, but the PS4 is tied up at the moment.

**Comment by marcussacana** [comment]
I'm glad that it worked, since the only output from the command is `zsh: killed     ./DirectPackageInstaller.Desktop` and the `dotnet` way still works, means that something is wrong with the executable made by .net runtime, and can be anything since are no details at all about the error.
My I ask you to test the build from this artifact?
https://github.com/marcussacana/DirectPackageInstaller/actions/runs/8760926760/artifacts/1431249281
Since this build is made in linux maybe the things may work...

If you wrote the bash script to run from the DPI directory (side by side with the executable) share with me and I may let it be included in the next builds for anyone trying use it as well.

Unfortally without hackintosh I can't do much support for the MacOS without detailed report as possible.

**Comment by marcussacana** [comment]
This zip contains the base structure used for the DPI build script, if you are able to adapt it to works with your fixes and we do a test build, I can accept a PR or include it if you just send it here.
https://github.com/marcussacana/DirectPackageInstaller/blob/main/Files/OSXAppBase.zip

**Comment by marcussacana** [comment]
Zip fixed.
