### ISSUE TITLE
How to setup AllDebrid

### ISSUE THREAD

**Issue by m1804-code** [marcussacana/DirectPackageInstaller#47]
First of all, thanks for the good application.
The question is how do I start the download via alldebrid in the background so I can close the app?
I have Proxy and Segmented turned off, and after adding the download and shutting down the app the ps4 stops downloading, and after a long while it displays an error that the content cannot be downloaded.

**Comment by marcussacana** [comment]
after set the api key and check the checkbox it should automatically works, You did right by disabling the proxy and segmented mode, if the download still being stopped maybe you found a bug, there are a good time that I didn't tested the alldebrid.
Since i'm without api key currently I can't test at all, I will try do something in the next month if I don't forget until the day.

**Comment by marcussacana** [comment]
Test the new version please.
