### ISSUE TITLE
Direct mode question and future rd support 

### ISSUE THREAD

**Issue by ananias47** [marcussacana/DirectPackageInstaller#49]
Hi to all

Firstly thank you for your great work

When i am trying the direct mode with binloader enabled when i quit the direct package installer app it stops from downloading on ps4. 
If i use the remote package installer first the download continue on ps4 with the direct package installer closed.
Am i missing something?? 

And second is it on plans to support real debrid?? (I have an account if you want help)
Thnx again in advance

**Comment by marcussacana** [comment]
Try with the new update.
About the realdebrid, I don't own an account that's why I never implemented it.
If you want you can send me your "API Private token" to ddtank.marcus@gmail.com and I can try implement it, but be warned that by sending this token to me you are giving me full access to your realdebird account until you click "Refresh" in this page: https://real-debrid.com/apitoken

**Comment by ananias47** [comment]
The problem with direct mode have fixed but still the ip doesn't auto fill on my android phone s23 ultra (android 14)
And one more question what is cnl support?? (it must be enabled on direct mode??)

**Comment by marcussacana** [comment]
IP Detection is not implemented in android, is different of how it works in PC, isn't impossible to do but I didn't yet.

**Comment by ananias47** [comment]
Ok my friend i send you on the email my private rd api key

**Comment by marcussacana** [comment]
You did right by saying, the email fall in my spam box.
Currently I'm in my job, I shoudn't give a look right now.

**Comment by ananias47** [comment]
Ok no problem. Only comment here when you are done so as not to use it from my side the rd

**Comment by marcussacana** [comment]
Support added, I'm not going to use your account anymore.
Feel free to test it too in the newest update.

**Comment by ananias47** [comment]
Thank you my friend for your great work again. Unfortunately I don't know when i Can test because i leave from ps4(it is not mine). One question what is the cnl support i must have enable it on wich mode?? Direct??
And one more on other dl mode rather than direct you say that we can close dpi app or close pc after press install how is that possible?? Because i think that especially the rar files firstly dl the files on pc unrae it and after send it on ps4.Am i wrong?

**Comment by marcussacana** [comment]
CNL is `Click'n Load` implementation for links behind the filecrypt service.
When you use the filecrypt this button may appear
![image](https://github.com/marcussacana/DirectPackageInstaller/assets/10576957/4c7c32ab-b675-4113-867a-ce26dc4ee9f5)
If you left the DPI "CNL Support" Enabled, by clicking it in that button the DPI will be able to automatically detect the pkg links from filecrypt and load it for you.
![image](https://github.com/marcussacana/DirectPackageInstaller/assets/10576957/02ed1b2c-a865-40e2-b37f-b01f8420bac9)

**Comment by ananias47** [comment]
And one more on other dl mode rather than direct you say that we can close dpi app or close pc after press install how is that possible?? Because i think that especially the rar files firstly dl the files on pc unrae it and after send it on ps4.Am i wrong?

**Comment by marcussacana** [comment]
Yeah, to be able to let the PS4 download the game without DPI you need to meet some requeriments in the download.
1 - The download link must be resumable (you meet this since you have realdebrid)
2 - The download must be a raw pkg file, compressed files can't be downloaded alone by the PS4
3 - The "Proxy Downloads" and "Segmented Download" options must be disabled
4 - Your PS4 needs to have internet access

If all conditions are meet, you can close the DPI and PS4 will be able to keep downloading.

It may look 'huh pretty rare' but the user are supposed to be using with his own uploaded backups, so we can suppose here as well that his storage keep the files in a good way for installing it.
