### ISSUE TITLE
1fichier support

### ISSUE THREAD

**Issue by Victorbry99** [marcussacana/DirectPackageInstaller#7]
1fichier is the most common host for fpkg, for example Opoisso uses only that. It would be wonderful if you can add the possibility to send 1fichier link directly. I tried to extract the direct link to the files without success sadly.

Also I noticed that using a vpn to arrive to the download page and then switching back to your connection before downloading, will not only bypass time limits but also remove file transfer speed limits. idk why but in my country 1fichier is capped at 500 kb/s or smth .Doing this way it downloads at full speed.

Thank for your great work, Marcus!

**Comment by marcussacana** [comment]
I'll think about it, we'll need proxies and it's always a pain in the ass to have an updated list of them, I don't know a proxy API with history to trust, if I add one, tomorrow it might stop working for example.

**Comment by seisdr** [comment]
`root@localhost:~# wine DirectPackageInstaller.exe

Unhandled Exception:
System.TypeLoadException: Could not load type of field 'DirectPackageInstaller.Main:PKGParser' (2) due to: Could not load file or assembly 'LibOrbisPkg, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:LibOrbisPkg, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:<none>
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'DirectPackageInstaller.Main:PKGParser' (2) due to: Could not load file or assembly 'LibOrbisPkg, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:LibOrbisPkg, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:<none>`

**Comment by marcussacana** [comment]
You shouldn't use wine, 
build from the source with monodevelop, open the DirectPackageInstallerLinux.sln
![image](https://user-images.githubusercontent.com/10576957/147416942-191b17eb-b25d-4af6-9011-f55088260063.png)

**Comment by seisdr** [comment]
Just running monodevelop in the root of the dir?

**Comment by marcussacana** [comment]
open the sln project with the monodevlop, it's a IDE, have a UI, you can use that to build the tool

**Comment by seisdr** [comment]
![Screenshot_٢٠٢١١٢٢٧-٢٣٣٤٤١](https://user-images.githubusercontent.com/45742462/147505584-3de4b390-14f1-4bed-9dd8-732ede936ea4.png)
See i can run it but if its cli only would be better cuz gui crashes on long run

**Comment by marcussacana** [comment]
I'm surprised you managed to start it on a cell phone.
Adding CLI support will need a refactoring in the code, it's not my priority at the moment but it could happen in the future.

**Comment by seisdr** [comment]
![Screenshot_٢٠٢١١٢٢٩-١٨١٣١٧](https://user-images.githubusercontent.com/45742462/147676652-6fa09e7c-3d52-45b8-9669-c82c790c1f46.png)

**Comment by Victorbry99** [comment]
nvm, I found a way for extracting direct links from 1fichier without making them expire.

The CLI version would be great, if it will ever happen in the future :)

**Comment by polybiusproxy** [comment]
> nvm, I found a way for extracting direct links from 1fichier without making them expire.
> 
> The CLI version would be great, if it will ever happen in the future :)

How?

**Comment by Victorbry99** [comment]
> > nvm, I found a way for extracting direct links from 1fichier without making them expire.
> > The CLI version would be great, if it will ever happen in the future :)
> 
> How?

With a browser extension that extract links from the page, for example "link klipper".

**Comment by polybiusproxy** [comment]
@marcussacana could this be possible, please?

**Comment by marcussacana** [comment]
I didn't see how he got it, with extension or not you can copy the download URL by right clicking on the button, but the DPI won't be able to install, first, the link only works once, after the first open connection the url expires, the DPI opens at least 4 connections to install each pkg, 2 to preview the pkg, 2 to install, where 1 connection is the HEAD to calculate the file size and one the GET itself to download the pkg.
For this, at least 4 proxies would have been used and new links created, assuming that the download does not lose connection in the middle of the transfer.

I can take a look into this if someone confirm if the 1fichier support partial requests in free downloads, I don't want implement the entire thing and just for discard the progress because of an artificial limitation of the server.

The correct method of using 1fichier with this tool is still with premium link generators, services like http://alldebrid.com/ will help you, of course, it's paid, but we don't have much choice here, alternatively, you can simply look for a better server when downloading the game.

It's in my best interest to make the tool as convenient as possible, but I can't do miracles given the server's limitations.

**Comment by marcussacana** [comment]
In fact I also have at hand a possibility to implement this feature using my personal paid account, but the method would leave loopholes for third party abuse due to the fact that my tool is open source, and I also don't have an estimate of how many downloads would be done on the my tool, so I'm worried about implementing the feature and a surreal number of downloads resulting in my account being suspended.

**Comment by Victorbry99** [comment]
yes, today I tried to use the direct link from 1fiecher with your tool but doesn't work because expires after 1 connection as you perfectly explained. thx anyway.

**Comment by marcussacana** [comment]
No, it does, the RPI connect first to get the pkg info, like the game icon and title id, then it's just impossible use the 1fichier free link in the RPI, the DPI maybe can act as a proxy to refresh the link automatically, but that's will be possible only if the 1fichier accept partial requests.

**Comment by Victorbry99** [comment]
I think it does accept partial requests, but I'm not sure.I noticed I can stop and resume download , but I don't know if it's relevant. So I followed a tutorial which says to do ```curl -I link```  and see Accept-Ranges. if it is omitted or gives value none, then not supported, if it gives in response ```Accept-Ranges: bytes``` it should.
So I did :
```$ curl -I https://a-14.1fichier.com/c118073942```

And give this response (so it should be ok?): 
```HTTP/1.1 200 OK
Date: Tue, 04 Jan 2022 16:50:37 GMT
Server: [Jun 14 2019 14:32:52]
Last-Modified: Thu, 23 Dec 2021 08:12:45 GMT
Content-Disposition: attachment; filename="[DLPSGAME.COM]-UP9000-CUSA17722_00-MARVELSSMMORALES-A0100-V0100.pkg"; filename*=UTF-8''%5bDLPSGAME.COM%5d-UP9000-CUSA17722_00-MARVELSSMMORALES-A0100-V0100.pkg
Content-Type: application/octet-stream
Access-Control-Allow-Origin: *
ETag: "3006e1b6d-8cd590000-61c42b09"
Connection: close
Accept-Ranges: bytes
Content-Length: 37804900352

**Comment by marcussacana** [comment]
![image](https://user-images.githubusercontent.com/10576957/148108512-1616a82c-3349-448c-9d7d-426b3d73075f.png)
I tried here, seems to support partial request, but don't worked when I used the proxy only to create the url.
The speed it has very slow to download since I used proxy even in the download, it took like 15 only to preview the pkg.
https://github.com/manuGMG/1fichier-dl/issues/42#issuecomment-997371800 said that the bypass method is fixed as well,  
this means: speed up this shit will be very hard.

**Comment by Victorbry99** [comment]
yah, it seems a pain in the ass. nvm then.

**Comment by polybiusproxy** [comment]
> I didn't see how he got it, with extension or not you can copy the download URL by right clicking on the button, but the DPI won't be able to install, first, the link only works once, after the first open connection the url expires, the DPI opens at least 4 connections to install each pkg, 2 to preview the pkg, 2 to install, where 1 connection is the HEAD to calculate the file size and one the GET itself to download the pkg. For this, at least 4 proxies would have been used and new links created, assuming that the download does not lose connection in the middle of the transfer.
> 
> I can take a look into this if someone confirm if the 1fichier support partial requests in free downloads, I don't want implement the entire thing and just for discard the progress because of an artificial limitation of the server.
> 
> The correct method of using 1fichier with this tool is still with premium link generators, services like http://alldebrid.com/ will help you, of course, it's paid, but we don't have much choice here, alternatively, you can simply look for a better server when downloading the game.
> 
> It's in my best interest to make the tool as convenient as possible, but I can't do miracles given the server's limitations.

I couldn't manage to get the direct link, however, it's possible to transfer it automatically to a host using Heroku to get the direct link and get it from there.
I tried this using my own host and the process was fast (transferring to the host and downloading).

And for the download cooldown, it is bypassed easily using RapidLeech.

**Comment by marcussacana** [comment]
With this no one should try bite me because lose of progress
![image](https://user-images.githubusercontent.com/10576957/149068708-0d1fa8b2-59d9-4dec-8f51-073f9eee7eb3.png)
will be a undocumented feature, because the 1fichier is a trash.
